name: Publish release
on:
  push:
    paths:
      - '**/**'  # 监控所有文件的更改
  pull_request:
    paths:
      - '**/**'  # 监控所有文件的更改

jobs:
  publish-release:
    uses: windy664/refinedarchitect/.github/workflows/publish-release.yml@v0.20.0
    secrets: inherit
    with:
      project-name: 'Refined Storage'
      gametests: true
